### ISSUE TITLE
Setting Procedure Variables

### ISSUE THREAD

**Issue by joefitzgerald** [landro/TesTcl#27]
I would like to be able to set variables in either `before` or `it` to set up the expected environment for my rule execution. I'm having issues determining how to do this, but it may be my lack of TCL expertise:

Given:
- I want to test with `event HTTP_REQUEST`
- In my actual iRule I need access to the request's port, which I can get at during the `CLIENT_ACCEPTED` event
- TesTcl does not support the `CLIENT_ACCEPTED` event or chaining of events
- I would like to be able to set `orig_port` from inside `before` or `it` blocks so that it is available during execution of the `HTTP_REQUEST` event

``` tcl
when CLIENT_ACCEPTED {
  set orig_port "[TCP::local_port]"
}
```

``` tcl
when HTTP_REQUEST {
  # Set x-forwarded-port Header
  if {[info exists orig_port]} {
    if { [HTTP::header exists "x-forwarded-port"] } {
      HTTP::header replace "x-forwarded-port" "$orig_port"
    } else {
      HTTP::header insert "x-forwarded-port" "$orig_port"
    }
  }
```

I have tried `set orig_port "80"` in `before` and `it`. I have tried `on orig_port return "80"`. None of my approaches have worked. How can I set variables at the scope of the rule procedure?

Thanks for the help!

**Comment by landro** [comment]
I believe this issue is closed by the variable support introduced in a5c289d30481cb6a17ba9c196aa4b1f34bfe3545
