### ISSUE TITLE
URI:: functionality support

### ISSUE THREAD

**Issue by samstep** [landro/TesTcl#30]
I would like request the URI namespace functionality support in TesTcl.

URI::basename - Extracts the basename part of a given uri string.
URI::compare - Compares two URI's for equality.
URI::decode - Returns a decoded version of a given URI.
URI::encode - Returns an encoded version of a given URI.
URI::host - Returns the host portion of a given URI.
URI::path - Returns the path portion of the given URI.
URI::port - Returns the host port from the given URI.
URI::protocol - Returns the protocol of the given URI.
URI::query - Returns the query string portion of the given URI or the value of a query string parameter.

**Comment by landro** [comment]
just pushed partial URI::encode support to master.

**Comment by landro** [comment]
Some of this has now been implemented
