### ISSUE TITLE
iRule procs and call command support

### ISSUE THREAD

**Issue by samstep** [landro/TesTcl#32]
I would like to request implementation of procs and "call" command. Starting from TMOS v 11.4 it is possible to define and use procs in an iRules (outside of "when" event) or in a separate iRule(not even associated with virtual server). procs defined inside iRules must be called using a new "call" command

References:

https://devcentral.f5.com/articles/getting-started-with-irules-procedures

https://devcentral.f5.com/questions/procedures-subroutines-for-irules-have-arrived-in-1140

https://devcentral.f5.com/wiki/irules.call.ashx

**Comment by djwales** [comment]
I have encountered this issue too. I have put together a basic example showing the problem. By removing the call keyword my test passes. If I put it back in to make it a valid iRule then my tests fail. I have attached the simple file and the associated test file.

[simple.txt](https://github.com/landro/TesTcl/files/223875/simple.txt)
[test_simple.txt](https://github.com/landro/TesTcl/files/223876/test_simple.txt)

**Comment by landro** [comment]
@djwales - thanks for the files. Could you please see if the call_command branch works for you?

**Comment by djwales** [comment]
Hi landro

I have just tried it and it works. Thanks for your effort. 

What are you planning in terms of putting the fix into the main code stream?

**Comment by landro** [comment]
fixed in 4b46e9177ff7f71165a183d7ac5018554c388375

**Comment by landro** [comment]
shipping now
