### ISSUE TITLE
tests should exit with a status reflecting whether they passed or not

### ISSUE THREAD

**Issue by nhemingway** [landro/TesTcl#36]
In order that test frameworks can tell which tests in a suite passed and failed, and to return a result for a whole test suite

**Comment by landro** [comment]
how about making the 'stats' (the one that can be used to print the number of failing tests) command return the number of failing tests, @nhemingway ?

**Comment by nhemingway** [comment]
Hi,

Locally, I added:

  ::tcl::exit $nbOfTestFailures

to stats as you suggest.  But that makes several of the TesTcl tests fail.

I'm digging as we speak, but not knowing tcl particularly, I'm open to
suggestions at this point....

Is there an IRC channel where we can discuss?

Neil

**Comment by landro** [comment]
Just committed 131a04aff243d505e078271c6380f23494bc9cc2 to 36_tests_should_exit_with_a_status_reflecting_whether_they_passed_or_not branch

Could you give that a shot, and see if it works for you @nhemingway ?

**Comment by nhemingway** [comment]
That works fine

**Comment by landro** [comment]
9c1e019ab90d2b8bab6ce2071f85524535bfbba9 fixes this issue

**Comment by nhemingway** [comment]
Excellent - thx

**Comment by nhemingway** [comment]
I'll have another issue and pull req for you once I've figured out how to get tcl to do IP address finagling
