### ISSUE TITLE
Error using HTTP::cookie

### ISSUE THREAD

**Issue by DeadZen** [landro/TesTcl#43]
"HTTP::cookie command is not implemented - use on HTTP::cookie..."

Is this not handled currently? Any plans on it?

**Comment by landro** [comment]
Not really @DeadZen. If you need it, check out irulehttp.tcl, and try implementing it. It shouldn't be too hard. Right now there is just a stub that @Sebastian-Brzuzek provided.

**Comment by olanystrom** [comment]
hi @landro can you provide a release for testcl with HTTP:cookie support? 1.0.13 is without cookies

**Comment by landro** [comment]
Just released 1.0.14 which contains cookie support provided by @kugg .

**Comment by kugg** [comment]
Its unfortunate that I didn't complete the full feature set on cookies but at least the basics are there. Once my PR was done I realised that there was a new version of F5 devices out with additional features that I had not implemented like custom cookie flags.
