### ISSUE TITLE
Error if test file is not found

### ISSUE THREAD

**Issue by dkaplan-pivotal** [landro/TesTcl#48]
If you pass a non-existent file to jtcl or you pass in a file that passes all tests, you get the same output (none).  This can mislead you into thinking your tests pass when in reality you're just not running them.  If you pass in a file that does not exist, it should error.

I suspect this requires a change to jtcl.  Is there some form of workaround?

**Comment by landro** [comment]
This seems to be an issue with jtcl - tclsh behaves differently:

 ➜  ~ tclsh abc.tcl
couldn't read file "abc.tcl": no such file or directory
➜  ~ jtcl abc.tcl

➜ 

Please report with jtcl project: https://github.com/jtcl-project/jtcl/issues
