### ISSUE TITLE
Update download link for jtcl-irule.jar

### ISSUE THREAD

**Issue by ThrowsException** [landro/TesTcl#52]
I fought trying to get my rules working when I noticed some operations like or and eq wasn't working. It appears the link on the Github page doesn't have these supported. I eventually got to http://landro.github.io/jtcl-irule/ and downloaded from bintray which seems to be working.

**Comment by landro** [comment]
Thanks for reporting @ThrowsException . The download on github contained an outdated jar file that didn't contain implementations for all the methods that f5 has added to standard tcl.
