### ISSUE TITLE
irules withour rule name { }

### ISSUE THREAD

**Issue by olanystrom** [landro/TesTcl#62]
I use a lot of iRules with ansibles [bigip_irule](https://docs.ansible.com/ansible/latest/modules/bigip_irule_module.html) and the irules and not wrapped in `rule name { IRULE }`
Is there a way to use testcl to test them?

Or do I have to make a builder-script to wrap the files in `rule NAME {}` to be able to test them?

**Comment by landro** [comment]
Currently this is not directly supported. Have you tried wrapping using the tcl source command?

**Comment by olanystrom** [comment]
That works fine. I have a tests-directory with the test and a .tcl that wraps with
```
rule name {
   source ../real_irule
}```

Now I have to figure out how to test my class-based stuff

**Comment by landro** [comment]
Have you checked https://github.com/landro/TesTcl/blob/master/examples/example_irule_classes.tcl

**Comment by olanystrom** [comment]
> Have you checked https://github.com/landro/TesTcl/blob/master/examples/example_irule_classes.tcl
> […](#)
Yes, and that makes it mostly succesful.

I had to rewrite some irules to be allowed with testcl.
```
if{ $lower_host eq "example.com"}
{
   do_something
}
```
that we have in production in F5:s are not allowed in the test, it has to be rewritten as

```
if{ $lower_host eq "example.com"} {
   do_something
}
```

also, it didnt like my use of [HTTP::host] inside strings. For example it didn't like
```
log local0. "Access to [HTTP::host] with uri [HTTP::uri]" 
```
At least I think that was the problem.
